<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="P:\Kistl\Tests\Kistl.IntegrationTests\Kistl.IntegrationTests.nunit" total="6" errors="0" failures="6" not-run="0" ignored="0" skipped="0" invalid="0" date="2009-04-21" time="10:31:27">
  <environment nunit-version="2.5.0.9015" clr-version="2.0.50727.3074" os-version="Microsoft Windows NT 6.0.6001 Service Pack 1" platform="Win32NT" cwd="P:\Kistl\Tests\Kistl.IntegrationTests" machine-name="KISTL" user="david" user-domain="kistl" />
  <culture-info current-culture="de-AT" current-uiculture="de-DE" />
  <test-suite name="P:\Kistl\Tests\Kistl.IntegrationTests\Kistl.IntegrationTests.nunit" executed="True" success="False" time="53.286" asserts="0">
    <results>
      <test-suite name="P:\Kistl\Tests\Kistl.IntegrationTests\bin\Debug\Kistl.IntegrationTests.dll" executed="True" success="False" time="53.206" asserts="0">
        <results>
          <test-suite name="Kistl" executed="True" success="False" time="53.202" asserts="0">
            <results>
              <test-suite name="IntegrationTests" executed="True" success="False" time="53.199" asserts="0">
                <failure>
                  <message><![CDATA[System.InvalidOperationException : Server did not started within 40 sec.]]></message>
                  <stack-trace><![CDATA[
Server stack trace:
bei Kistl.Server.Server.Start(KistlConfig config) in p:\Kistl\Kistl.Server\Server.cs:Zeile 53.
bei System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
bei System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
bei System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)

Exception rethrown at [0]:
bei Kistl.IntegrationTests.SetUp.Init() in p:\Kistl\Tests\Kistl.IntegrationTests\SetUp.cs:Zeile 47.
]]></stack-trace>
                </failure>
                <results>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.Collections.Generic.ICollection`1[System.Int32])" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.Collections.Generic.ICollection`1[System.Nullable`1[System.Int32]])" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.Collections.Generic.ICollection`1[System.String])" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.Int32)" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.Nullable`1[System.Int32])" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-case name="Kistl.IntegrationTests.TypeRefs.should_convert_types_correctly.when_calling_ToRef_on_a_Type(System.String)" executed="True" success="False" time="0.000" asserts="0">
                    <failure>
                      <message><![CDATA[TestFixtureSetUp failed in SetUp]]></message>
                      <stack-trace />
                    </failure>
                  </test-case>
                  <test-suite name="when_calling_ToRef_on_a_Type" executed="True" success="False" time="0.000" asserts="0" />
                  <test-suite name="should_convert_types_correctly" executed="True" success="False" time="0.000" asserts="0" />
                  <test-suite name="TypeRefs" executed="True" success="False" time="0.000" asserts="0" />
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>